version: '3'

services:
    es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
        container_name: es01
        environment:
            - node.name=es01
            - http.cors.allow-origin=*
            - http.cors.enabled=true
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es02,es03
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - network.host=0.0.0.0
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9201:9200
        volumes:
            - ./.docker/data/es01:/usr/share/elasticsearch/data
    es02:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
        container_name: es02
        environment:
            - node.name=es02
            - http.cors.allow-origin=*
            - http.cors.enabled=true
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es01,es03
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - network.host=0.0.0.0
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./.docker/data/es02:/usr/share/elasticsearch/data
    es03:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
        container_name: es03
        environment:
            - node.name=es03
            - http.cors.allow-origin=*
            - http.cors.enabled=true
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es01,es02
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - network.host=0.0.0.0
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./.docker/data/es03:/usr/share/elasticsearch/data
    kib7:
        build:
            context: .
            dockerfile: ./.docker/Dockerfile.kib7
        env_file:
            - ./.docker/kib7.env
        ports:
            - 5602:5601
