services:
  setup:
    build:
      target: dev
    volumes:
      - ./:/app
  app:
    build:
      target: dev
    environment:
      - GATEWAY_HOST=api-dummy:8080
    volumes:
      - ./:/app
  queue-watcher:
    build:
      target: dev
    volumes:
      - ./:/app
