services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        volumes:
            - ./:/app
            - ./config.php:/app/config.php
            - ./.docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        ports:
            - '8888:80'
        stdin_open: true
        tty: true
        extra_hosts:
            host.docker.internal: host-gateway
