services:
  setup:
    build:
      target: dev
    volumes:
      - ./:/app
  app:
    build:
      target: dev
    volumes:
      - ./:/app
  queue-watcher:
    build:
      target: dev
    volumes:
      - ./:/app
