version: '3'
services:

    opensearch:
        image: opensearchproject/opensearch:latest
        container_name: opensearch
        environment:
            - cluster.name=opensearch-cluster
            - node.name=opensearch
            - discovery.type=single-node
            - DISABLE_SECURITY_PLUGIN=true
            - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
                hard: 65536
        volumes:
            - opensearch-data1:/usr/share/opensearch/data
        ports:
            - '9200:9200'
            - '9600:9600' # required for Performance Analyzer
        networks:
            - opensearch-net

    opensearch-dashboards:
        build:
            context: .
            dockerfile: Dockerfile.opensearch-dashboards
        container_name: opensearch-dashboards
        ports:
            - '5601:5601'
        expose:
            - '5601'
        environment:
            OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
        networks:
            - opensearch-net
        depends_on:
            - opensearch
    api-dummy:
        image: elifesciences/api-dummy:34fa87c3706aa83dc8690297efe4928905a2ddce
        container_name: api-dummy
        ports:
            - '5002:8080'
        networks:
            - opensearch-net
    gearman:
        image: artefactual/gearmand:latest
        container_name: gearman
        ports:
            - '4730:4730'
        networks:
            - opensearch-net

    localstack:
        image: localstack/localstack:latest
        environment:
            - SERVICES=sqs
            - AWS_DEFAULT_REGION=eu-central-1
            - EDGE_PORT=4566
            - HOSTNAME_EXTERNAL=localstack
        ports:
            - '4566:4566'
        networks:
            - opensearch-net

    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - API_DUMMY_HOSTNAME=api-dummy
            - GEARMAN_HOSTNAME=gearman
        volumes:
            - ..:/app
            - ./config.php.dist:/app/config.php
        ports:
            - '8888:80'
        networks:
            - opensearch-net
        depends_on:
            - opensearch
            - gearman
            - localstack
        stdin_open: true
        tty: true

volumes:
    opensearch-data1:

networks:
    opensearch-net:
        driver: bridge
