version: '3'
services:

    opensearch:
        build:
            context: .
            dockerfile: Dockerfile.opensearch

        container_name: opensearch
        restart: on-failure
        environment:
            - cluster.name=opensearch-cluster
            - node.name=opensearch
            - discovery.type=single-node
            - DISABLE_SECURITY_PLUGIN=true
            - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
                hard: 65536
        volumes:
            - opensearch-data1:/usr/share/opensearch/data
        ports:
            - '9200:9200'
            - '9600:9600' # required for Performance Analyzer
        networks:
            - opensearch-net
    api-dummy:
        image: elifesciences/api-dummy:c66acdb349850d31b4e7a0f578ffdc87e2fada96
        container_name: api-dummy
        ports:
            - '5002:8080'
        networks:
            - opensearch-net

    localstack:
        image: localstack/localstack:2.3.2
        environment:
            - SERVICES=sqs
            - AWS_DEFAULT_REGION=eu-central-1
            - HOSTNAME=localstack
            - HOSTNAME_EXTERNAL=localstack
        ports:
            - "127.0.0.1:4566:4566"            # LocalStack Gateway
            - "127.0.0.1:4510-4559:4510-4559"  # external services port range
        networks:
            - opensearch-net

    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - GEARMAN_HOST=gearman
        volumes:
            - ..:/app
            - ./config.php.dist:/app/config.php
        ports:
            - '8888:80'
        networks:
            - opensearch-net
        depends_on:
            - opensearch
            - localstack
        stdin_open: true
        tty: true

volumes:
    opensearch-data1:

networks:
    opensearch-net:
        driver: bridge
