<?php

namespace Puli;

use Puli\Discovery\Api\Discovery;
use Puli\Discovery\Binding\Initializer\ResourceBindingInitializer;
use Puli\Discovery\JsonDiscovery;
use Puli\Manager\Api\Server\ServerCollection;
use Puli\Repository\Api\ResourceRepository;
use Puli\Repository\JsonRepository;
use Puli\UrlGenerator\Api\UrlGenerator;
use Puli\UrlGenerator\DiscoveryUrlGenerator;
use RuntimeException;

/**
 * Creates Puli's core services.
 *
 * This class was auto-generated by Puli.
 *
 * IMPORTANT: Before modifying the code below, set the "factory.auto-generate"
 * configuration key to false:
 *
 *     $ puli config factory.auto-generate false
 *
 * Otherwise any modifications will be overwritten!
 */
class GeneratedPuliFactory
{
    /**
     * Creates the resource repository.
     *
     * @return ResourceRepository The created resource repository.
     */
    public function createRepository()
    {
        if (!interface_exists('Puli\Repository\Api\ResourceRepository')) {
            throw new RuntimeException('Please install puli/repository to create ResourceRepository instances.');
        }

        $repo = new JsonRepository(__DIR__.'/path-mappings.json', __DIR__.'/..', true);

        return $repo;
    }

    /**
     * Creates the resource discovery.
     *
     * @param ResourceRepository $repo The resource repository to read from.
     *
     * @return Discovery The created discovery.
     */
    public function createDiscovery(ResourceRepository $repo)
    {
        if (!interface_exists('Puli\Discovery\Api\Discovery')) {
            throw new RuntimeException('Please install puli/discovery to create Discovery instances.');
        }

        $discovery = new JsonDiscovery(__DIR__.'/bindings.json', array(
            new ResourceBindingInitializer($repo),
        ));

        return $discovery;
    }

    /**
     * Creates the URL generator.
     *
     * @param Discovery $discovery The discovery to read from.
     *
     * @return UrlGenerator The created URL generator.
     */
    public function createUrlGenerator(Discovery $discovery)
    {
        if (!interface_exists('Puli\UrlGenerator\Api\UrlGenerator')) {
            throw new RuntimeException('Please install puli/url-generator to create UrlGenerator instances.');
        }

        $generator = new DiscoveryUrlGenerator($discovery, array());

        return $generator;
    }

    /**
     * Returns the order in which the installed packages should be loaded
     * according to the override statements.
     *
     * @return string[] The sorted package names.
     */
    public function getPackageOrder()
    {
        $order = array(
            'elife/search',
            'aws/aws-sdk-php',
            'beberlei/assert',
            'doctrine/annotations',
            'doctrine/cache',
            'doctrine/instantiator',
            'doctrine/lexer',
            'elasticsearch/elasticsearch',
            'elife/api',
            'elife/api-validator',
            'guzzlehttp/guzzle',
            'guzzlehttp/promises',
            'guzzlehttp/psr7',
            'guzzlehttp/ringphp',
            'guzzlehttp/streams',
            'hamcrest/hamcrest-php',
            'jms/metadata',
            'jms/parser-lib',
            'jms/serializer',
            'justinrainbow/json-schema',
            'mockery/mockery',
            'monolog/monolog',
            'mtdowling/jmespath.php',
            'myclabs/deep-copy',
            'paragonie/random_compat',
            'phpcollection/phpcollection',
            'phpdocumentor/reflection-common',
            'phpdocumentor/reflection-docblock',
            'phpdocumentor/type-resolver',
            'phpoption/phpoption',
            'phpspec/prophecy',
            'phpunit/php-code-coverage',
            'phpunit/php-file-iterator',
            'phpunit/php-text-template',
            'phpunit/php-timer',
            'phpunit/php-token-stream',
            'phpunit/phpunit',
            'phpunit/phpunit-mock-objects',
            'pimple/pimple',
            'propel/propel',
            'psr/http-message',
            'psr/log',
            'puli/composer-plugin',
            'puli/discovery',
            'puli/repository',
            'puli/url-generator',
            'ramsey/uuid',
            'react/promise',
            'sebastian/code-unit-reverse-lookup',
            'sebastian/comparator',
            'sebastian/diff',
            'sebastian/environment',
            'sebastian/exporter',
            'sebastian/global-state',
            'sebastian/object-enumerator',
            'sebastian/recursion-context',
            'sebastian/resource-operations',
            'sebastian/version',
            'seld/jsonlint',
            'silex/silex',
            'symfony/browser-kit',
            'symfony/config',
            'symfony/console',
            'symfony/debug',
            'symfony/dom-crawler',
            'symfony/event-dispatcher',
            'symfony/filesystem',
            'symfony/finder',
            'symfony/http-foundation',
            'symfony/http-kernel',
            'symfony/polyfill-mbstring',
            'symfony/process',
            'symfony/psr-http-message-bridge',
            'symfony/routing',
            'symfony/translation',
            'symfony/validator',
            'symfony/yaml',
            'webmozart/assert',
            'webmozart/expression',
            'webmozart/glob',
            'webmozart/json',
            'webmozart/path-util',
            'zendframework/zend-diactoros',
        );

        return $order;
    }
}
