name: Create PR to update elife api dependencies to latest
on:
  workflow_dispatch:
  schedule:
  - cron: '0 4 * * 1'

jobs:
  update-api-dummy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - id: api-sdk-old-version
      run: echo api-sdk-old-version=$(jq -r '.packages[]|select(.name == "elife/api-sdk").source.reference' < composer.lock) >> $GITHUB_OUTPUT

    - id: api-old-version
      run: echo api-old-version=$(jq -r '.packages[]|select(.name == "elife/api").version' < composer.lock) >> $GITHUB_OUTPUT

    - name: Check for api-sdk updates
      run: |
        docker compose run --no-deps setup composer install
        docker compose run --no-deps setup composer update 'elife/api' 'elife/api-sdk' --no-suggest --no-interaction

    - id: api-sdk-new-version
      run: echo api-sdk-new-version=$(jq -r '.packages[]|select(.name == "elife/api-sdk").source.reference' < composer.lock) >> $GITHUB_OUTPUT

    - id: api-new-version
      run: echo api-new-version=$(jq -r '.packages[]|select(.name == "elife/api").version' < composer.lock) >> $GITHUB_OUTPUT

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        add-paths: composer.lock
        commit-message: |
          Update elife API packages:
          - `elife/api` from `${{ steps.api-old-version.outputs.api-version }}` to `${{ steps.api-new-version.outputs.api-version }}`
          - `elife/api-sdk` from `${{ steps.api-sdk-old-version.outputs.api-sdk-version }}` to `${{ steps.api-sdk-new-version.outputs.api-sdk-version }}`
        branch: update-api-sdk
        title: Update elife API packages(`elife/api`:`${{ steps.get-api-version.outputs.api-version }}` - `elife/api-sdk`:`${{ steps.get-api-sdk-version.outputs.api-sdk-version }}`)
        body: |
          Update elife API packages:
          - `elife/api` from `${{ steps.api-old-version.outputs.api-version }}` to `${{ steps.api-new-version.outputs.api-version }}`
          - `elife/api-sdk` from `${{ steps.api-sdk-old-version.outputs.api-sdk-version }}` to `${{ steps.api-sdk-new-version.outputs.api-sdk-version }}`
